<!DOCTYPE html>
<html lang="es-CO">
<head>
	<meta charset="utf-8">
	<title>Pruebas paramétricas - Parte I</title>

	<!-- mobile responsive meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="El espacio perfecto para Biólogos y R">
	
	<meta name="author" content="&lt;/R Biólogos&gt;">
	<meta name="generator" content="Hugo 0.111.3">

	<!-- plugins -->
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/bootstrap/bootstrap.min.css">
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/themify-icons/themify-icons.css">
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/magnific-popup/magnific-popup.css">
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/slick/slick.css">
	
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anaheim%7cQuattrocento&#43;Sans:400,700&amp;display=swap">
	

	<!-- Main Stylesheet -->
	
	<link rel="stylesheet" href="https://rbiologos.com/css/style.min.css" media="screen">

	<!-- Custom stylesheet - for your changes -->
	
  <link rel="stylesheet" href="https://rbiologos.com/css/custom.min.css" media="screen">

	<!--Favicon-->
	<link rel="shortcut icon" href="https://i.ibb.co/XL1r8wK/2.png" type="image/x-icon">
	<link rel="icon" href="https://i.ibb.co/XL1r8wK/2.png" type="image/x-icon">

	
	<!-- Global Site Tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-N49JEEK9KF"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'G-N49JEEK9KF');
	</script>
	

</head>


<body id="body" data-spy="scroll" data-target=".navbar" data-offset="55">
  <div id="content">
    
<!-- preloader start -->
<div class="preloader">
  
  <img src="https://i.ibb.co/BjJWHb3/preloader.gif" alt="preloader" width="300">
  
</div>
<!-- preloader end -->



<section class="sticky-top navigation">
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-dark">
			<a class="navbar-brand p-0" href="/">
				
				<img class="lozad" data-src="https://i.ibb.co/XL1r8wK/2.png" alt="R Biólogos" height="42">
				
			</a>

			<button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navigation">
				<ul class="navbar-nav ml-auto">
					
					<li class="nav-item">
            <a class="nav-link" href="/#https://rbiologos.com/">Inicio</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#blog">Blog</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#team">Equipo</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#about">¿Qué somos?</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#feature">¿Qué hacemos?</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#contact">Contacto</a>
					</li>
					
					
				</ul></div>
				
				
				<select id="select-language" onchange="location = this.value;">
					
					
					
					
					
					
					
					
					<option id="es" value="https://rbiologos.com/blog/a015/" selected>ES
					</option>
					
					
					
					
					
					
					
					
				</select>
				
			
			<script>
  (function() {
    var id = '06c75f9c-882f-11eb-a152-0242ac130002';
    var ci_search = document.createElement('script');
    ci_search.type = 'text/javascript';
    ci_search.async = true;
    ci_search.src = 'https://cse.expertrec.com/api/js/ci_common.js?id=' + id;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ci_search, s);
  })();
</script><ci-search></ci-search>
		</nav>
	</div>
</section>


<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 text-center">
        <h1>Pruebas paramétricas - Parte I</h1>
        <ul class="list-inline mb-50">
          <li class="list-inline-item"><a href="/author/david-vanegas/">David Vanegas</a></li>
          <li class="list-inline-item">viernes, nov. 26, 2021</li>
        </ul>
        <img class="img-fluid mb-50 lozad" data-src="https://i.ibb.co/svwd3XW/ES.png" alt="blog-image">
      </div>
      <div class="col-lg-8 offset-lg-2">
        <div class="post-single-content">
          
<script src="https://rbiologos.com/blog/a015/index.es_files/header-attrs/header-attrs.js"></script>


<p>Se conoce como estadística paramétrica a las pruebas que se basan en el muestreo de una población con parámetros específicos como la normalidad y la homocedasticidad</p>
<div id="contenido-del-post" class="section level1">
<h1>Contenido del post</h1>
<ul>
<li><a href="#1">Introducción</a></li>
<li><a href="#2">Test Z</a></li>
<li><a href="#3">Test F</a></li>
<li><a href="#4">Test T de Student</a></li>
<li><a href="#5">Resumen</a></li>
<li><a href="#6">Bibliografía</a></li>
<li><a href="#7">Más información</a></li>
</ul>
</div>
<div id="introducción" class="section level1">
<h1>Introducción</h1>
<p><a name="1"></a></p>
<p>Las pruebas paramétricas asumen distribuciones estadísticas subyacentes a los datos. Por tanto, deben cumplirse algunas condiciones de validez, de modo que el resultado de la prueba paramétrica sea fiable. Por ejemplo, la prueba t de Student para dos muestras independientes será fiable solo si cada muestra se ajusta a una distribución normal y si las varianzas son homogéneas.</p>
<center>
<img src="https://i.ibb.co/G0bnfWW/tongue.gif" width="350" />
</center>
<p><br></p>
<p>Las ventajas de las pruebas paramétricas son:</p>
<ul>
<li>Sensibles a rasgos de los datos recolectados</li>
<li>Estimaciones probabilísticas más exactas</li>
<li>Tienen una mayor eficiencia estadística</li>
<li>Mayor poder estadístico</li>
</ul>
<p>Las desventajas de las purebas paramétricas son:</p>
<ul>
<li>Más complicadas de calcular</li>
<li>Solo se pueden aplicar si se cumplen sus supuestos</li>
</ul>
<p>Algunos de los análisis más populares son:</p>
<table>
<thead>
<tr class="header">
<th align="left">Análisis</th>
<th align="left">Paramétrico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Describir un grupo</td>
<td align="left">μ - σ2</td>
</tr>
<tr class="even">
<td align="left">Comparar un grupo a un valor</td>
<td align="left">T Student de una muestra</td>
</tr>
<tr class="odd">
<td align="left">Comparar medias en dos grupos</td>
<td align="left">T Student de dos muestras</td>
</tr>
<tr class="even">
<td align="left">Comparar medias en dos grupos apareados</td>
<td align="left">T Student apareada</td>
</tr>
<tr class="odd">
<td align="left">Comparar medias en tres o más grupos</td>
<td align="left">ANOVA</td>
</tr>
<tr class="even">
<td align="left">Correlación entre dos variables</td>
<td align="left">Pearson (Lineal)</td>
</tr>
</tbody>
</table>
</div>
<div id="test-z" class="section level1">
<h1>Test Z</h1>
<p><a name="2"></a></p>
<p>Se utiliza para determinar el grado de significatividad estadística de las diferencias entre las medias de dos conjuntos de datos. Se utiliza cuando las muestras son amplias (de más de 30 individuos aproximadamente) e independientes (esto es, no correlacionadas).</p>
<p>Cuando se tiene una población con distribución normal (o aproximada a la normal) y se conoce la varianza es posible emplear el estadístico Z para la prueba de hipótesis. Se parte del supuesto que <em>H0: μ0 = μ1</em>.</p>
<center>
<img src="https://i.ibb.co/R3m3cT2/original.gif" width="350" />
</center>
<p><br></p>
<blockquote>
<p>Recordemos que las varianzas son una medida de dispersión, es decir, qué tan dispersos están los datos con respecto a la media. Los valores más altos representan mayor dispersión.</p>
</blockquote>
<p>Para realizar nuestra prueba de hipótesis con la función <res>z.test()</res> necesitamos instalar el paquete <res>BSDA</res>. Los parámetros de la función los podemos encontrar en este <a href="https://www.rdocumentation.org/packages/BSDA/versions/1.2.1/topics/z.test">LINK</a></p>
<pre class="r"><code>z.test(
  x, # Vector numérico; Se permiten NA e Inf, pero se eliminarán.
  y = NULL, # Vector numérico; Se permiten NA e Inf, pero se eliminarán
  alternative = &quot;two.sided&quot;, # Indica la especificación de la hipótesis alternativa, &quot;greater&quot;, &quot;less&quot; o &quot;two.sided&quot;
  mu = 0, # Un solo número que representa el valor de la media o la diferencia en las medias especificadas por la hipótesis nula
  sigma.x = NULL, # Un solo número que representa la desviación estándar de la población para x
  sigma.y = NULL, # Un solo número que representa la desviación estándar de la población para y
  conf.level = 0.95 # Nivel de confianza para el intervalo de confianza, restringido a estar entre cero y uno
)</code></pre>
<p>Veamos entonces algunos ejemplos con algunas consideraciones sobre nuestros datos</p>
<div id="una-población-normal-con-desviación-estándar-conocida" class="section level3">
<h3>Una población normal con desviación estándar conocida</h3>
<p>Se desea contrastar con un nivel de significancia del 5% la hipótesis de que la estatura media de los hombres de 18 o más años de un país es igual a <strong><em>175</em></strong>, contra la alternativa que es menor que <strong><em>175</em></strong>. Suponiendo que la desviación estándar es de <strong><em>4.5</em></strong>.</p>
<blockquote>
<p>Asumiremos que los datos tienen una distribución normal</p>
</blockquote>
<pre class="r"><code># Cargamos el paquete
library(BSDA)

# Creamos nuestros datos
muestra &lt;- c(167,167,168,168,168,169,171,172,173,175,175,175,177,182)

z.test(x = muestra,
       alternative = &quot;less&quot;, 
       mu = 175,
       sigma.x = sd(muestra), 
       conf.level = 0.95)</code></pre>
<pre><code>## 
##  One-sample z-Test
## 
## data:  muestra
## z = -2.5652, p-value = 0.005156
## alternative hypothesis: true mean is less than 175
## 95 percent confidence interval:
##        NA 173.8981
## sample estimates:
## mean of x 
##  171.9286</code></pre>
<p>Así, de acuerdo a nuestros resultados podemos rechazar <em>Ho</em>, ya que existe suficiente evidencia de que la estatura media de los hombres en ese país es menor que <strong><em>175</em></strong>.</p>
</div>
<div id="dos-poblaciones-normales-con-varianzas-conocidas" class="section level3">
<h3>Dos poblaciones normales con varianzas conocidas</h3>
<p>Un dueño de una fábrica tiene un pedido muy grande y para llevarlo a cabo necesita conocer cuál de las dos máquinas para realizar el proceso trabaja con mayor velocidad, el intuye que la maquina 2 es más efectiva y para ello hace una prueba, toman el tiempo de fabricación en minutos de 10 productos en cada máquina. ¿Es posible que la máquina 2 tenga un mejor tiempo de producción que la máquina 1 usando un nivel de significancia de 0.05?</p>
<center>
<img src="https://i.ibb.co/WgML6X6/vikings-river.gif" width="350" />
</center>
<p><br></p>
<blockquote>
<p>Asumiremos que los datos tienen una distribución normal</p>
</blockquote>
<p>Hipótesis:</p>
<ul>
<li><em>Ho: μ1 - μ2 = 0</em></li>
<li><em>Ha: μ2 &gt; μ1</em></li>
</ul>
<pre class="r"><code>maquina_1 &lt;- c(14,13,15,14,17,16,15,16,13,17)
maquina_2 &lt;- c(16,15,14,17,12,17,15,16,15,14)

z.test(x = maquina_1,
       y = maquina_2,
       alternative = &quot;greater&quot;,
       mu = 0,
       sigma.x = sd(maquina_1), # sd() función para calcular desviación estándar
       sigma.y = sd(maquina_2),
       conf.level = 0.95)</code></pre>
<pre><code>## 
##  Two-sample z-Test
## 
## data:  maquina_1 and maquina_2
## z = -0.14834, p-value = 0.559
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  -1.208837        NA
## sample estimates:
## mean of x mean of y 
##      15.0      15.1</code></pre>
<p>Como podemos observar en nuestros resultados, nuestra hipótesis nula fue rechazada, en su lugar nuestra hipótesis alternativa es aceptada, en conclusión, podemos decir que existe evidencia que la <em>máquina 2</em> es más rápida que la <em>máquina 1</em>.</p>
</div>
</div>
<div id="test-f" class="section level1">
<h1>Test F</h1>
<p><a name="4"></a></p>
<p>El test F de Fisher calcula la relación entre la varianza más grande y la varianza más pequeña. Usamos la prueba F cuando queremos verificar dónde las medias de tres o más grupos son diferentes o no. Se utiliza para evaluar si las varianzas de dos poblaciones (A y B) son iguales. Para ello utilizaremos la función <res>var.test()</res> con los argumentos que veremos a continuación y que podrás consultar en este <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/var.test"><em>LINK</em></a>, con las siguientes hipótesis planteadas</p>
<ul>
<li><p><em>H0: σ1<sup>2</sup> = σ2<sup>2</sup></em> (Las varianzas poblacionales son iguales)</p></li>
<li><p><em>H1: σ1<sup>2</sup> ≠ σ2<sup>2</sup></em> (Las varianzas de población <em>no</em> son iguales)</p></li>
</ul>
<pre class="r"><code>var.test(formula, # Fórmula de la forma lhs ~ rhs donde lhs es una variable numérica que da los valores de los datos y rhs un factor con dos niveles que dan los grupos correspondientes.
         data, # Matriz opcional o marco de datos que contiene las variables en la fórmula fórmula. Por defecto, las variables se toman del entorno (fórmula)
         subset, # Vector opcional que especifica un subconjunto de observaciones que se utilizarán.
         na.action) # Función que indica lo que debería suceder cuando los datos contienen NA</code></pre>
<p>Veamos un ejemplo, con las edades de los investigadores de dos grupos de estudio en la Universidad</p>
<center>
<img src="https://i.ibb.co/tX7JKVf/vikingbattle.gif" width="350" />
</center>
<p><br></p>
<pre class="r"><code># Definimos los dos grupos
data &lt;- data.frame(valores = c(18, 19, 22, 25, 27, 28, 41, 45, 51, 55,
                            14, 15, 15, 17, 18, 22, 25, 25, 27, 34),
                   grupo = rep(c(&#39;A&#39;, &#39;B&#39;), each = 10))

# Realizamos un F-test para determinar si las varianzas son iguales
var.test(valores ~ grupo, data = data)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  valores by grupo
## F = 4.3871, num df = 9, denom df = 9, p-value = 0.03825
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##   1.089699 17.662528
## sample estimates:
## ratio of variances 
##           4.387122</code></pre>
<p>Así, el estadístico de la prueba F es <strong><em>4.3871</em></strong> y el <em>valor p</em> correspondiente es <strong><em>0.03825</em></strong>. Dado que este valor p es menor que <strong><em>.05</em></strong>, rechazaríamos la hipótesis nula. Esto significa que, tenemos suficiente evidencia para decir que las dos variaciones de población <em>NO</em> son iguales.</p>
</div>
<div id="test-t-de-student" class="section level1">
<h1>Test T de student</h1>
<p><a name="3"></a></p>
<p>Es un estadístico para comparar la media de una muestra <em>(x̄)</em> con la de la población <em>(μ)</em> sin necesidad de conocer su varianza <em>(σ)</em>. El hecho de que los valores promedio de cada grupo no sean iguales no implica que haya evidencias de una diferencia significativa. Dado que cada grupo tiene su propia variabilidad, aunque el tratamiento no sea eficaz, las medias muestrales no tienen por qué ser exactas. Este test fue desarrollado por <em>William Sealy Gosset</em>, mejor conocido por su pseudónimo <em>Student</em>.</p>
<center>
<img src="https://i.ibb.co/TPvj3Vs/battle.gif" width="350" />
</center>
<p><br></p>
<p>Para utilizar la t de Student es necesario que se cumplan los siguientes supuestos:</p>
<ul>
<li>La muestra es aleatoria</li>
<li>Se desconoce la <em>σ</em></li>
<li>Los datos tienen una distribución normal o n ≥ 30</li>
<li>Los errores tienen una distribución normal</li>
<li>Cuando se comparan dos distribuciones las varianzas son iguales <em>(σ1 = σ2)</em></li>
</ul>
<p>La función requerida para este cálculo es <res>t.test()</res>, podrás encontrar más información de la función en este <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/t.test"><em>LINK</em></a>. Veamos sus parámetros</p>
<pre class="r"><code>t.test(x, y = NULL, # Un vector numérico (no vacío) de valores de datos
       alternative = c(&quot;two.sided&quot;, &quot;less&quot;, &quot;greater&quot;), # Especificando la hipótesis alternativa
       mu = 0, # Número que indica el valor real de la media (o la diferencia de medias si está realizando una prueba de dos muestras).
       paired = FALSE, # Un indicador lógico que indica si desea una prueba t emparejada.
       var.equal = FALSE, # Variable lógica que indica si se deben tratar las dos varianzas como iguales
       conf.level = 0.95) # Nivel de confianza del intervalo.</code></pre>
<div id="test-t-de-student-para-una-muestra" class="section level3">
<h3>Test T de student para una muestra</h3>
<p>Permite comprobar si es posible aceptar que la media de la población es un valor determinado. Se toma una muestra y el Test permite evaluar si es razonable mantener la Hipótesis nula de que la media es tal valor.</p>
<p>Se trata de un test paramétrico; o sea, parte de la suposición de que la variable analizada en el conjunto de la población sigue una variabilidad, una distribución como la de la campana de Gauss. Por lo tanto, podemos pensar que la distribución normal es un buen modelo de esa población.</p>
<p>Para este ejemplo utilizaremos la variable largo del sépalo (sepal.lenght) de la especie <em>I. setosa</em> de la base <em>Iris</em>, asumiendo que cumple con los criterios establecidos para este tipo de test, como lo vimos en nuestro anterior <a href="https://rbiologos.com/blog/a014/"><em>POST</em></a></p>
<center>
<img src="https://i.ibb.co/ckQPHxC/vikings.gif" width="350" />
</center>
<p><br></p>
<p>Así, asumiremos que un investigador propone que a partir de sus observaciones considera que la longitud del sépalo de <em>I. setosa</em> es de 5.3cm</p>
<pre class="r"><code># Filtamos la información para nuestro ejercicio
datos &lt;- iris[iris$Species == &quot;setosa&quot;, ]$Sepal.Length

t.test(datos, 
       alternative = &quot;two.sided&quot;,
       mu = 5.3, 
       conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  datos
## t = -5.8977, df = 49, p-value = 3.363e-07
## alternative hypothesis: true mean is not equal to 5.3
## 95 percent confidence interval:
##  4.905824 5.106176
## sample estimates:
## mean of x 
##     5.006</code></pre>
<p>Por tanto, el resultado nos presenta que la media teórica no corresponde a los datos que se estudiaron. El valor de la media con un intervalo de confianza del 95% situa a la media entre los valores de <strong><em>4.905824</em></strong> y <strong><em>5.106176</em></strong>, con una media aritmética de <strong><em>5.006</em></strong>, por lo cual la propuesta del investigador es inválida.</p>
</div>
<div id="test-t-de-student-para-dos-muestras-de-medias-poblacionales-independientes" class="section level3">
<h3>Test T de student para dos muestras de medias poblacionales independientes</h3>
<p>Para realizar este tipo de análisis las observaciones tienen que ser independientes unas de las otras. Para ello el muestreo debe ser aleatorio y el tamaño de la muestra inferior al 10% de la población.</p>
<p>Los pasos a seguir para realizar un t-test de medias independientes son:</p>
<ol style="list-style-type: decimal">
<li>Establecer las hipótesis</li>
</ol>
<p>Hipótesis nula <em>(Ho)</em>: por lo general es la hipótesis escéptica, la que considera que no hay diferencia o cambio. Suele contener en su definición el símbolo =. En el caso de comparar dos medias independientes la hipótesis nula considera que <em>μ1 = μ2</em>.</p>
<p>Hipótesis alternativa <em>(Ha)</em>: considera que el valor real de la media poblacional es mayor, menor o distinto del valor que establece la <em>Ho</em>. Suele contener los símbolos <em>&gt;, &lt;, ≠</em>. En el caso de comparar dos medias independientes la hipótesis alternativa considera que <em>μ1 ≠ μ2</em>.</p>
<ol start="2" style="list-style-type: decimal">
<li>Calcular el estadístico (parámetro estimado)</li>
</ol>
<p>El estadístico es el valor que se calcula a partir de la muestra y que se quiere extrapolar a la población de origen. En este caso es la diferencia de las medias muestrales <em>(x̄1 - x̄2)</em>.</p>
<ol start="3" style="list-style-type: decimal">
<li>Determinar el tipo de test, una o dos colas</li>
</ol>
<p>Los test de hipótesis pueden ser de una cola o de dos colas. Si la hipótesis alternativa emplea <em>“&gt;”</em> o <em>“&lt;”</em> se trata de un test de una cola, en el que solo se analizan desviaciones en un sentido. Si la hipótesis alternativa es del tipo “diferente de” se trata de un test de dos colas, en el que se analizan posibles desviaciones en las dos direcciones. Solo se emplean test de una cola cuando se sabe con seguridad que las desviaciones de interés son en un sentido y únicamente si se ha determinado antes de observar la muestra, no a posteriori.</p>
<center>
<img src="https://i.ibb.co/xFKdJVK/lagertha.gif" width="350" />
</center>
<p><br></p>
<p><strong><em>Ejemplo</em></strong></p>
<p>Ahora, exploraremos la relación entre las especies del género <em>Iris</em> (species) y el largo de su sépalo (Sepal.Length) de la base de datos <em>Iris</em>. Una es una variable categórica y la otra es una variable continua. Para tener una idea rápida de si uno afecta al otro, podemos mirar el diagrama de caja y en la cual asumiremos que cumplen con los criterios que deben cumplir para hacer un test paramétrico como lo vimos en nuestro anterior <a href="https://rbiologos.com/blog/a014/"><em>POST</em></a></p>
<pre class="r"><code># Cargamos las librerías necesarias
library(ggplot2)

# Filtramos la información, vamos a eliminar los datos de la especie I. virginica y observamos los datos
datos2 &lt;- iris[iris$Species != &quot;virginica&quot;,]
head(datos2)</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<pre class="r"><code># Recuerda que la base Iris está por defecto en un computadora 
ggplot(datos2, aes(x = Species, y = Sepal.Length)) + 
  geom_boxplot() + 
  labs(x = &quot;Especies&quot;, 
       y = &quot;Largo del sépalo&quot;)+
  theme_bw()</code></pre>
<p><img src="https://rbiologos.com/blog/a015/index.es_files/figure-html/unnamed-chunk-8-1.png" width="100%" /></p>
<p>Ahora calculemos el <em>p valor</em> a partir del estadístico <em>t student</em>. R tiene una función integrada que permite realizar t-test para una o dos muestras, tanto con corrección (en caso de que las varianzas no sean iguales) como sin ella. Esta función devuelve tanto el <em>p-value</em> del test como el intervalo de confianza para la verdadera diferencia de medias.</p>
<pre class="r"><code># Filtramos la información para realizar el test
x &lt;- iris[iris$Species == &quot;setosa&quot;, ]$Sepal.Length
y &lt;- iris[iris$Species == &quot;versicolor&quot;, ]$Sepal.Length

t.test(x, 
       y, 
       paired = FALSE, 
       alternative = &quot;two.sided&quot;, 
       var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x and y
## t = -10.521, df = 86.538, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.1057074 -0.7542926
## sample estimates:
## mean of x mean of y 
##     5.006     5.936</code></pre>
<p>Como podemos observar en los resultados anteriores, el valor de p es <strong><em>2.2<sup>16</sup></em></strong> es significativamente más bajo que nuestro umbral del 5%. Por tanto, podemos rechazar la hipótesis nula y aceptar la alternativa.</p>
<p>Según la hipótesis alternativa, los valores de <em>Sepal.Length</em> para varias especies son estadísticamente diferentes entre sí, es decir, los valores están claramente separados entre las diferentes clases de especies.</p>
</div>
<div id="test-t-de-student-para-dos-muestras-de-medias-poblacionales-dependientes-pareadas" class="section level3">
<h3>Test T de student para dos muestras de medias poblacionales dependientes (pareadas)</h3>
<p>Dos medias son dependientes o pareadas cuando proceden de grupos o muestras dependientes, esto es, cuando existe una relación entre las observaciones de las muestras. Este escenario ocurre a menudo cuando los resultados se generan a partir de los mismos individuos bajo condiciones distintas.</p>
<p>Las pruebas pareadas tienen la ventaja frente a los independientes de que se puede controlar mejor la variación no sistematica, ya que se bloquean al estar examinando los mismos individuos dos veces, no dos grupos de individuos distintos.</p>
<center>
<img src="https://i.ibb.co/VQ7zKqD/ubbe.gif" width="350" />
</center>
<p><br></p>
<p>Veamos un ejemplo, donde el programa de biología ha decidido contratar a un nuevo profesor para un grupo de estudio. Para decidir si al cabo de un año mantienen su contrato se selecciona aleatoriamente a 10 estudiantes y se resgistran sus avances en el proyecto (0 a 5, donde 5 es la mayor nota) al inicio del año, al final del año se volverá a registrar esos mismos 10 estudiantes. En vista de los datos obtenidos ¿Hay diferencia significativa entre el rendimiento de los estudiantes tras un año de estudiar con el nuevo profesor?</p>
<pre class="r"><code># Creamos las variables deseadas
notas &lt;- data.frame(
          estudiante = c(1:10),
          antes = c(2.9, 3.5, 2.8, 4.5, 3.7, 2.9, 2.6, 3.5, 4.4, 1.3),
          despues = c(2.7, 3.6, 2.0, 4.2, 3.6, 2.0, 2.0, 3.5, 4.6, 1.1)
        )
head(notas)</code></pre>
<pre><code>##   estudiante antes despues
## 1          1   2.9     2.7
## 2          2   3.5     3.6
## 3          3   2.8     2.0
## 4          4   4.5     4.2
## 5          5   3.7     3.6
## 6          6   2.9     2.0</code></pre>
<p>Al tratarse de datos pareados, interesa conocer la diferencia en cada par de observaciones, al igual que otros ejemplos asumiremos el cumplimiento de los supuestos par pruebas paramétricas.</p>
<p>R contiene la función <res>t.test()</res> que realiza un test con datos pareados si se le indica en el argumento. R calcula automáticamente las diferencias para cada evento, asumiendo que se las posiciones de cada vector se corresponden a los datos de un mismo individuo. Está función calcula además el intervalo de confianza para la diferencia de medias.</p>
<pre class="r"><code>t.test(x = notas$antes, 
       y = notas$despues, 
       alternative = &quot;two.sided&quot;,
       mu = 0, 
       paired = TRUE, # Datos pareados
       conf.level = 0.95)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  notas$antes and notas$despues
## t = 2.3702, df = 9, p-value = 0.0419
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.01276315 0.54723685
## sample estimates:
## mean of the differences 
##                    0.28</code></pre>
<p>Como el <em>p-value</em> &gt; <em>α</em>, no hay evidencias estadísticas significativas para rechazar <em>H0</em> en favor de <em>HA</em>. Por lo tanto, no se pude considerar que el rendimiento de los estudiantes haya cambiado, al parecer este profe no conservará su puesto.</p>
</div>
<div id="test-t-de-student-para-dos-muestras-independientes-con-varianzas-no-homogéneas" class="section level3">
<h3>Test T de Student para dos muestras independientes con varianzas no homogéneas</h3>
<p>Para este ejemplo vamos a suponer que nuestros datos anteriores son muestras normales pero no tienen varianzas iguales. Por ello, procederemos a realizar el test de Welch. Los siguientes vectores muestran los puntajes de los exámenes de los estudiantes de cada grupo</p>
<pre class="r"><code>booklet &lt;- c(90, 85, 88, 89, 94, 91, 79, 83, 87, 88, 91, 90)
no_booklet &lt;- c(67, 90, 71, 95, 88, 83, 72, 66, 75, 86, 93, 84)

t.test(booklet, 
       no_booklet)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  booklet and no_booklet
## t = 2.2361, df = 14.354, p-value = 0.04171
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   0.3048395 13.8618272
## sample estimates:
## mean of x mean of y 
##  87.91667  80.83333</code></pre>
<p>De nuestros resultados podemos ver que el estadístico de prueba t es <strong><em>2.2361</em></strong> y el <em>valor p</em> correspondiente es <strong><em>0.04171</em></strong>.</p>
<p>Dado que este <em>valor p</em> es menor que <strong><em>.05</em></strong>, podemos rechazar la hipótesis nula y concluir que existe una diferencia estadísticamente significativa en las puntuaciones medias de los exámenes entre los dos grupos.</p>
</div>
</div>
<div id="resumen" class="section level1">
<h1>Resumen</h1>
<p><a name="5"></a></p>
<p>Como pudimos leer en este post, hay varios estadísticos que nos permitirán tratar nuestros datos paramétricos, recordemos que deben cumplir ciertos criterios para ser llamados de esta manera.</p>
<p>En nuestro próximo post veremos otro análisis muy importante como lo es el <em>Análisis de Varianzas</em> o conocido como <em><strong><em>ANOVA</em></strong></em>.</p>
<p>Hasta pronto y gracias por acompañarños, recuerda que si tienes alguna duda o comentario, nos puedes escribir a través de nuestras redes sociales o nuestro correo</p>
<p>¡¡¡Hasta pronto!!!</p>
<center>
<img src="https://i.ibb.co/vX335L7/dead.gif" width="350" />
</center>
<p><br></p>
</div>
<div id="bibliografía" class="section level1">
<h1>Bibliografía</h1>
<p><a name="6"></a></p>
<ul>
<li><p><a href="https://www.dicenlen.eu/es/diccionario/entradas/prueba-z">Prueba Z</a></p></li>
<li><p><a href="https://rstudio-pubs-static.s3.amazonaws.com/607000_89fe88b16d4047ad9f968f0e862273dd.html#1">13. Pruebas de hipótesis para la media de una población</a></p></li>
<li><p><a href="https://rpubs.com/will10/558310">Prueba de hipotésis</a></p></li>
<li><p><a href="https://jllopisperez.com/2012/12/16/test-de-la-t-de-student-para-una-muestra/">Test de la t de Student para una muestra</a></p></li>
<li><p><a href="https://www.rpubs.com/tonosan/param_no_param">Estadística paramétrica y no paramétrica</a></p></li>
<li><p><a href="https://svaditya.github.io/oldblog/chi_square_and_t_tests_on_iris_data.html">Chi-Square and T tests on Iris Data</a></p></li>
<li><p><a href="https://rpubs.com/Joaquin_AR/218467">T-test</a></p></li>
<li><p><a href="https://www.statology.org/welch-t-test-in-r/">How to Perform Welch’s t-Test in R</a></p></li>
<li><p><a href="https://www.statology.org/f-test-in-r/">How to Perform an F-Test in R</a></p></li>
<li><p><a href="https://la.mathworks.com/discovery/linear-regression.html">¿Qué es la regresión lineal?</a></p></li>
</ul>
</div>
<div id="más-información" class="section level1">
<h1>Más información</h1>
<p><a name="7"></a></p>
<p>Estos análisis se han realizado utilizando el software R (v.4.1.0) y Rstudio (v. 1.4.1717)</p>
<p>Recuerda que todos nuestros códigos están almacenados en <a href="https://github.com/RBiologos/Posts">GitHub</a></p>
<center>
<img src="https://i.ibb.co/DpKmR1k/github.png" width="350" />
</center>
</div>

        </div>
        
        

<div class="social-share pt-4">
	<h4>Comparte:</h4>
	
	<a class="resp-sharing-button__link" href="https://facebook.com/sharer/sharer.php?u=https%3a%2f%2frbiologos.com%2fblog%2fa015%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--facebook resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path d="M18.77 7.46H14.5v-1.9c0-.9.6-1.1 1-1.1h3V.5h-4.33C10.24.5 9.5 3.44 9.5 5.32v2.15h-3v4h3v12h5v-12h3.85l.42-4z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="https://twitter.com/intent/tweet/?text=Pruebas%20param%c3%a9tricas%20-%20Parte%20I&amp;url=https%3a%2f%2frbiologos.com%2fblog%2fa015%2f"
		target="_blank" rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--twitter resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M23.44 4.83c-.8.37-1.5.38-2.22.02.93-.56.98-.96 1.32-2.02-.88.52-1.86.9-2.9 1.1-.82-.88-2-1.43-3.3-1.43-2.5 0-4.55 2.04-4.55 4.54 0 .36.03.7.1 1.04-3.77-.2-7.12-2-9.36-4.75-.4.67-.6 1.45-.6 2.3 0 1.56.8 2.95 2 3.77-.74-.03-1.44-.23-2.05-.57v.06c0 2.2 1.56 4.03 3.64 4.44-.67.2-1.37.2-2.06.08.58 1.8 2.26 3.12 4.25 3.16C5.78 18.1 3.37 18.74 1 18.46c2 1.3 4.4 2.04 6.97 2.04 8.35 0 12.92-6.92 12.92-12.93 0-.2 0-.4-.02-.6.9-.63 1.96-1.22 2.56-2.14z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="https://plus.google.com/share?url=https%3a%2f%2frbiologos.com%2fblog%2fa015%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--google resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M11.37 12.93c-.73-.52-1.4-1.27-1.4-1.5 0-.43.03-.63.98-1.37 1.23-.97 1.9-2.23 1.9-3.57 0-1.22-.36-2.3-1-3.05h.5c.1 0 .2-.04.28-.1l1.36-.98c.16-.12.23-.34.17-.54-.07-.2-.25-.33-.46-.33H7.6c-.66 0-1.34.12-2 .35-2.23.76-3.78 2.66-3.78 4.6 0 2.76 2.13 4.85 5 4.9-.07.23-.1.45-.1.66 0 .43.1.83.33 1.22h-.08c-2.72 0-5.17 1.34-6.1 3.32-.25.52-.37 1.04-.37 1.56 0 .5.13.98.38 1.44.6 1.04 1.84 1.86 3.55 2.28.87.23 1.82.34 2.8.34.88 0 1.7-.1 2.5-.34 2.4-.7 3.97-2.48 3.97-4.54 0-1.97-.63-3.15-2.33-4.35zm-7.7 4.5c0-1.42 1.8-2.68 3.9-2.68h.05c.45 0 .9.07 1.3.2l.42.28c.96.66 1.6 1.1 1.77 1.8.05.16.07.33.07.5 0 1.8-1.33 2.7-3.96 2.7-1.98 0-3.54-1.23-3.54-2.8zM5.54 3.9c.33-.38.75-.58 1.23-.58h.05c1.35.05 2.64 1.55 2.88 3.35.14 1.02-.08 1.97-.6 2.55-.32.37-.74.56-1.23.56h-.03c-1.32-.04-2.63-1.6-2.87-3.4-.13-1 .08-1.92.58-2.5zM23.5 9.5h-3v-3h-2v3h-3v2h3v3h2v-3h3" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="mailto:?subject=Pruebas%20param%c3%a9tricas%20-%20Parte%20I&amp;body=https%3a%2f%2frbiologos.com%2fblog%2fa015%2f" target="_self"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--email resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M22 4H2C.9 4 0 4.9 0 6v12c0 1.1.9 2 2 2h20c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zM7.25 14.43l-3.5 2c-.08.05-.17.07-.25.07-.17 0-.34-.1-.43-.25-.14-.24-.06-.55.18-.68l3.5-2c.24-.14.55-.06.68.18.14.24.06.55-.18.68zm4.75.07c-.1 0-.2-.03-.27-.08l-8.5-5.5c-.23-.15-.3-.46-.15-.7.15-.22.46-.3.7-.14L12 13.4l8.23-5.32c.23-.15.54-.08.7.15.14.23.07.54-.16.7l-8.5 5.5c-.08.04-.17.07-.27.07zm8.93 1.75c-.1.16-.26.25-.43.25-.08 0-.17-.02-.25-.07l-3.5-2c-.24-.13-.32-.44-.18-.68s.44-.32.68-.18l3.5 2c.24.13.32.44.18.68z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link"
		href="https://reddit.com/submit/?url=https%3a%2f%2frbiologos.com%2fblog%2fa015%2f&amp;resubmit=true&amp;title=Pruebas%20param%c3%a9tricas%20-%20Parte%20I" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--reddit resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M24 11.5c0-1.65-1.35-3-3-3-.96 0-1.86.48-2.42 1.24-1.64-1-3.75-1.64-6.07-1.72.08-1.1.4-3.05 1.52-3.7.72-.4 1.73-.24 3 .5C17.2 6.3 18.46 7.5 20 7.5c1.65 0 3-1.35 3-3s-1.35-3-3-3c-1.38 0-2.54.94-2.88 2.22-1.43-.72-2.64-.8-3.6-.25-1.64.94-1.95 3.47-2 4.55-2.33.08-4.45.7-6.1 1.72C4.86 8.98 3.96 8.5 3 8.5c-1.65 0-3 1.35-3 3 0 1.32.84 2.44 2.05 2.84-.03.22-.05.44-.05.66 0 3.86 4.5 7 10 7s10-3.14 10-7c0-.22-.02-.44-.05-.66 1.2-.4 2.05-1.54 2.05-2.84zM2.3 13.37C1.5 13.07 1 12.35 1 11.5c0-1.1.9-2 2-2 .64 0 1.22.32 1.6.82-1.1.85-1.92 1.9-2.3 3.05zm3.7.13c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9.8 4.8c-1.08.63-2.42.96-3.8.96-1.4 0-2.74-.34-3.8-.95-.24-.13-.32-.44-.2-.68.15-.24.46-.32.7-.18 1.83 1.06 4.76 1.06 6.6 0 .23-.13.53-.05.67.2.14.23.06.54-.18.67zm.2-2.8c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm5.7-2.13c-.38-1.16-1.2-2.2-2.3-3.05.38-.5.97-.82 1.6-.82 1.1 0 2 .9 2 2 0 .84-.53 1.57-1.3 1.87z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="whatsapp://send?text=Pruebas%20param%c3%a9tricas%20-%20Parte%20I%20https%3a%2f%2frbiologos.com%2fblog%2fa015%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--whatsapp resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M20.1 3.9C17.9 1.7 15 .5 12 .5 5.8.5.7 5.6.7 11.9c0 2 .5 3.9 1.5 5.6L.6 23.4l6-1.6c1.6.9 3.5 1.3 5.4 1.3 6.3 0 11.4-5.1 11.4-11.4-.1-2.8-1.2-5.7-3.3-7.8zM12 21.4c-1.7 0-3.3-.5-4.8-1.3l-.4-.2-3.5 1 1-3.4L4 17c-1-1.5-1.4-3.2-1.4-5.1 0-5.2 4.2-9.4 9.4-9.4 2.5 0 4.9 1 6.7 2.8 1.8 1.8 2.8 4.2 2.8 6.7-.1 5.2-4.3 9.4-9.5 9.4zm5.1-7.1c-.3-.1-1.7-.9-1.9-1-.3-.1-.5-.1-.7.1-.2.3-.8 1-.9 1.1-.2.2-.3.2-.6.1s-1.2-.5-2.3-1.4c-.9-.8-1.4-1.7-1.6-2-.2-.3 0-.5.1-.6s.3-.3.4-.5c.2-.1.3-.3.4-.5.1-.2 0-.4 0-.5C10 9 9.3 7.6 9 7c-.1-.4-.4-.3-.5-.3h-.6s-.4.1-.7.3c-.3.3-1 1-1 2.4s1 2.8 1.1 3c.1.2 2 3.1 4.9 4.3.7.3 1.2.5 1.6.6.7.2 1.3.2 1.8.1.6-.1 1.7-.7 1.9-1.3.2-.7.2-1.2.2-1.3-.1-.3-.3-.4-.6-.5z" />
				</svg>
			</div>
		</div>
	</a>
	
	<a class="resp-sharing-button__link" href="https://telegram.me/share/url?text=Pruebas%20param%c3%a9tricas%20-%20Parte%20I&amp;url=https%3a%2f%2frbiologos.com%2fblog%2fa015%2f"
		target="_blank" rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--telegram resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M.707 8.475C.275 8.64 0 9.508 0 9.508s.284.867.718 1.03l5.09 1.897 1.986 6.38a1.102 1.102 0 0 0 1.75.527l2.96-2.41a.405.405 0 0 1 .494-.013l5.34 3.87a1.1 1.1 0 0 0 1.046.135 1.1 1.1 0 0 0 .682-.803l3.91-18.795A1.102 1.102 0 0 0 22.5.075L.706 8.475z" />
				</svg>
			</div>
		</div>
	</a>

</div>
        
        
        <div class="mt-5">
          
        </div>
      </div>
    </div>
  </div>
</section>


  </div><!-- end Contact Area -->
<footer id="footer" class="section-bg">
	<div class="container">
		<div class="row wow fadeInUp" data-wow-duration="500ms">
			<div class="col-lg-12">

			

                        <!-- Footer Social Links -->
				<div class="social-icon"><h1><center                                                    >Social</center></h1>
					<ul class="list-inline">
						
						<li class="list-inline-item"><a href="https://www.instagram.com/rbiologos/" target="blank"><i class="ti-instagram" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://www.facebook.com/rbiologos" target="blank"><i class="ti-facebook" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://github.com/RBiologos/Posts" target="blank"><i class="ti-github" target="blank"></i></a></li>
						
					</ul>
				</div>
				
				<center><img src="https://i.ibb.co/SwJkbqh/2.png" alt="R Biólogos" height="200" /></center>
	
				<!-- copyright -->
				<div class="copyright text-center">
				        
					<a href="https://rbiologos.com/">
					</a>
					<br>
					<p1>Copyright © 2020 Modificado por <a href="https://davidvanegal.github.io/">David Vanegas</a> bajo la plantilla <a href="https://themefisher.com">Themefisher</a> de <a href="https://gethugothemes.com">HUGO</a></p1>
				</div>
				
			</div>
		</div>
	</div>
</footer>
<!-- /footer -->

<!-- Google Map API -->


<!-- JS Plugins -->

<script src="https://rbiologos.com/plugins/jquery/jquery.min.js"></script>

<script src="https://rbiologos.com/plugins/bootstrap/bootstrap.min.js"></script>

<script src="https://rbiologos.com/plugins/slick/slick.min.js"></script>

<script src="https://rbiologos.com/plugins/shuffle/shuffle.min.js"></script>

<script src="https://rbiologos.com/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>

<script src="https://rbiologos.com/plugins/lazy-load/lozad.min.js"></script>

<script src="https://rbiologos.com/plugins/google-map/map.js"></script>


<!-- Main Script -->

<script src="https://rbiologos.com/js/script.min.ab3836b70bc45170e8ff6dd572ee5e8e761ac8376daf9ceb40f760dfb6f2cce49672517da770a0049959f5fc93337e13.js" integrity="sha384-qzg2twvEUXDo/23Vcu5ejnYayDdtr5zrQPdg37byzOSWclF9p3CgBJlZ9fyTM34T"></script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
<div id="js-cookie-box" class="cookie-box cookie-box-hide">
	This site uses cookies. By continuing to use this website, you agree to their use. <span id="js-cookie-button" class="btn btn-transparent">I Accept</span>
</div>
<script>
	(function ($) {
		const cookieBox = document.getElementById('js-cookie-box');
		const cookieButton = document.getElementById('js-cookie-button');
		if (!Cookies.get('cookie-box')) {
			cookieBox.classList.remove('cookie-box-hide');
			cookieButton.onclick = function () {
				Cookies.set('cookie-box', true, {
					expires:  2 
				});
				cookieBox.classList.add('cookie-box-hide');
			};
		}
	})(jQuery);
</script>
</body>

</html>
