<!DOCTYPE html>
<html lang="es-CO">
<head>
	<meta charset="utf-8">
	<title>Relaciones lineales</title>

	<!-- mobile responsive meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="El espacio perfecto para Biólogos y R">
	
	<meta name="author" content="&lt;/R Biólogos&gt;">
	<meta name="generator" content="Hugo 0.111.3">

	<!-- plugins -->
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/bootstrap/bootstrap.min.css">
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/themify-icons/themify-icons.css">
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/magnific-popup/magnific-popup.css">
	
	<link rel="stylesheet" href="https://rbiologos.com/plugins/slick/slick.css">
	
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anaheim%7cQuattrocento&#43;Sans:400,700&amp;display=swap">
	

	<!-- Main Stylesheet -->
	
	<link rel="stylesheet" href="https://rbiologos.com/css/style.min.css" media="screen">

	<!-- Custom stylesheet - for your changes -->
	
  <link rel="stylesheet" href="https://rbiologos.com/css/custom.min.css" media="screen">

	<!--Favicon-->
	<link rel="shortcut icon" href="https://i.ibb.co/XL1r8wK/2.png" type="image/x-icon">
	<link rel="icon" href="https://i.ibb.co/XL1r8wK/2.png" type="image/x-icon">

	
	<!-- Global Site Tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-N49JEEK9KF"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'G-N49JEEK9KF');
	</script>
	

</head>


<body id="body" data-spy="scroll" data-target=".navbar" data-offset="55">
  <div id="content">
    
<!-- preloader start -->
<div class="preloader">
  
  <img src="https://i.ibb.co/BjJWHb3/preloader.gif" alt="preloader" width="300">
  
</div>
<!-- preloader end -->



<section class="sticky-top navigation">
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-dark">
			<a class="navbar-brand p-0" href="/">
				
				<img class="lozad" data-src="https://i.ibb.co/XL1r8wK/2.png" alt="R Biólogos" height="42">
				
			</a>

			<button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navigation">
				<ul class="navbar-nav ml-auto">
					
					<li class="nav-item">
            <a class="nav-link" href="/#https://rbiologos.com/">Inicio</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#blog">Blog</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#team">Equipo</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#about">¿Qué somos?</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#feature">¿Qué hacemos?</a>
					</li>
					
					
					<li class="nav-item">
            <a class="nav-link" href="/#contact">Contacto</a>
					</li>
					
					
				</ul></div>
				
				
				<select id="select-language" onchange="location = this.value;">
					
					
					
					
					
					
					
					
					<option id="es" value="https://rbiologos.com/blog/a016/" selected>ES
					</option>
					
					
					
					
					
					
					
					
				</select>
				
			
			<script>
  (function() {
    var id = '06c75f9c-882f-11eb-a152-0242ac130002';
    var ci_search = document.createElement('script');
    ci_search.type = 'text/javascript';
    ci_search.async = true;
    ci_search.src = 'https://cse.expertrec.com/api/js/ci_common.js?id=' + id;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ci_search, s);
  })();
</script><ci-search></ci-search>
		</nav>
	</div>
</section>


<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 text-center">
        <h1>Relaciones lineales</h1>
        <ul class="list-inline mb-50">
          <li class="list-inline-item"><a href="/author/david-vanegas/">David Vanegas</a></li>
          <li class="list-inline-item">miércoles, dic. 22, 2021</li>
        </ul>
        <img class="img-fluid mb-50 lozad" data-src="https://i.ibb.co/XDRQpnz/ES.png" alt="blog-image">
      </div>
      <div class="col-lg-8 offset-lg-2">
        <div class="post-single-content">
          
<script src="https://rbiologos.com/blog/a016/index.es_files/header-attrs/header-attrs.js"></script>


<p>Cuando se evalúa la relación entres dos variables, es importante determinar cómo se relacionan estas, por tanto, una relación lineal es un término que se utiliza para describir una dicha relación.</p>
<center>
<img src="https://i.ibb.co/3c7tH9L/office.gif" width="350" />
</center>
<p><br></p>
<div id="contenido-del-post" class="section level1">
<h1>Contenido del post</h1>
<ul>
<li><a href="#1">Introducción</a></li>
<li><a href="#2">Regresión lineal simple</a></li>
<li><a href="#3">Correlación lineal</a>
<ul>
<li><a href="#4">Correlación de Pearson</a></li>
<li><a href="#5">coeficiente de determinación</a></li>
<li><a href="#6">Gráfico de correlaciones</a></li>
</ul></li>
<li><a href="#7">Resumen</a></li>
<li><a href="#8">Bibliografía</a></li>
<li><a href="#9">Anexos</a></li>
<li><a href="#10">Más información</a></li>
</ul>
</div>
<div id="introducción" class="section level1">
<h1>Introducción</h1>
<p><a name="1"></a></p>
<p>La regresión lineal es una técnica de modelado estadístico que se emplea para describir una variable de respuesta continua como una función de una o varias variables predictoras. Puede ayudar a comprender y predecir el comportamiento de sistemas complejos o a analizar datos biológicos.</p>
<center>
<img src="https://i.ibb.co/bNP3kYW/dance.gif" width="350" />
</center>
<p><br></p>
<p>A continuación veremos algunas formas de la regresión con algunos ejemplos para que practiques</p>
</div>
<div id="regresión-lineal-simple" class="section level1">
<h1>Regresión lineal simple</h1>
<p><a name="2"></a></p>
<p>En un modelo de regresión lineal simple tratamos de explicar la relación que existe entre la variable respuesta <strong><em>Y</em></strong> y una única variable explicativa <strong><em>X</em></strong>.</p>
<p>Para trabajar el modelo de regresión lineal simple, es necesario trabajar con la función <em><res>lm()</res></em>, con los argumentos que vamos a mostrar a continuación, sin embargo, podemos tener más información de la función en este <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm"><em>LINK</em></a></p>
<pre class="r"><code>lm(formula, # Objeto de clase &#39;fórmula&#39;: una descripción simbólica del modelo que se va a ajustar.
   data, # Marco de datos, lista o entorno opcional que contiene las variables en el modo
   na.action) # Función que indica lo que debería suceder cuando los datos contienen NA</code></pre>
<p>vamos a poner en contexto una situación en donde tenemos las especies de plantas <em>Iris</em>. En este caso, nos va a interesar conocer la relación entre el largo del sépalo y el largo del pétalo.</p>
<pre class="r"><code># Cargamos el paquete dplyr para organizar los datos y ggplot2 para graficar
library(dplyr)
library(ggplot2)
data(&quot;iris&quot;)

# Veamos el comportamiento de los datos en una gráfica
iris %&gt;% 
        ggplot(aes(x = Sepal.Length,
                   y = Petal.Length)) +
        geom_point()+
        theme_bw()</code></pre>
<p><img src="https://rbiologos.com/blog/a016/index.es_files/figure-html/unnamed-chunk-2-1.png" width="100%" /></p>
<p>Como podemos observar en este gráfico la tendencia lineal es clara, sin embargo, es necesario encontrar los valores estadísticos para afirmar este comportamiento.</p>
<pre class="r"><code>modelo_lineal &lt;- lm(Sepal.Length ~ Petal.Length, # De esta manera se formula la relación entre dos variables
                    data = iris)

summary(modelo_lineal)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sepal.Length ~ Petal.Length, data = iris)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.24675 -0.29657 -0.01515  0.27676  1.00269 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   4.30660    0.07839   54.94   &lt;2e-16 ***
## Petal.Length  0.40892    0.01889   21.65   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4071 on 148 degrees of freedom
## Multiple R-squared:   0.76,  Adjusted R-squared:  0.7583 
## F-statistic: 468.6 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Mediante este ejemplo podemos interpretar varios valores mostrados en el summary. Empecemos, el valor de <em>R<sup>2</sup></em> indica que el modelo calculado explica el <strong><em>76%</em></strong> de la variabilidad presente en la variable respuesta (Ancho del sépalo) mediante la variable independiente (Largo del sépalo), con un <em>p-value</em> de <strong><em>2.2e-16</em></strong>) el cual determina que sí es significativamente superior la varianza explicada por el modelo en comparación a la varianza total. Es el parámetro que determina si el modelo es significativo y por lo tanto se puede aceptar la veracidad del modelo.</p>
<center>
<img src="https://i.ibb.co/5Rjzcb8/party.gif" width="350" />
</center>
<p><br></p>
<p>Alternativamente, podemos agregar a nuestro gráfico la línea de tendencia lineal de nuestro modelo, mediante la función <res>geom_smooth()</res> para poder observar el comportamiento de nuestros resultados y verificarlos</p>
<pre class="r"><code>ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Petal.Length)) +
        geom_point() +
        labs(x = &quot;Largo del sépalo&quot;, y = &quot;Largo del pétalo&quot;) +
        geom_smooth(method = &quot;lm&quot;, se = FALSE, color = &quot;red&quot;) +
        theme_bw()</code></pre>
<p><img src="https://rbiologos.com/blog/a016/index.es_files/figure-html/unnamed-chunk-4-1.png" width="100%" /></p>
<p>De esta manera, podemos observar que nuestra línea de tendencia tiene cierto comportamiento en relación a la nube de puntos de la relación de nuestros datos, por lo cual, podemos inferir que nuestro modelo de regresión lineal si se está cumpliendo.</p>
</div>
<div id="correlación-lineal" class="section level1">
<h1>Correlación lineal</h1>
<p><a name="3"></a></p>
<p>En ocasiones nos puede interesar estudiar si existe o no algún tipo de relación entre dos variables aleatorias. Las relaciones o asociaciones de este tipo entre variables se denominan correlaciones; y están medidas en escalas ordinales o de intervalos. En particular, nos interesa cuantificar la intensidad de la relación lineal entre dos variables.</p>
<center>
<img src="https://i.ibb.co/sqLH8kf/the-office.gif" width="350" />
</center>
<p><br></p>
<p>Un coeficiente de correlación mide el grado en que dos variables tienden a cambiar al mismo tiempo. Cuando el aumento de una de las variables viene acompañado del aumento de la otra, se trata de una correlación positiva o directa y viceversa. Una Correlación perfecta se da cuando todos los puntos de un diagrama de dispersión forman una linea recta perfecta. Estas correlaciones perfectas (positivas o negativas) prácticamente no existen en biología.</p>
<p>Los coeficientes de correlación describen tanto la fuerza como la dirección de la relación y se pueden calcular mediante métodos paramétricos y no paramétricos. Y su calculo en R se puede hacer a través de la función <res>cor()</res>.</p>
<blockquote>
<p>La correlación nos indica el signo y magnitud de la tendencia entre dos variables.</p>
</blockquote>
<p>El signo nos indica la dirección de la relación</p>
<p>– Un valor positivo indica una relación directa o positiva,</p>
<p>– Un valor negativo indica relación inversa o negativa,</p>
<p>– Un valor nulo indica que no existe una tendencia entre ambas variables (puede ocurrir que no exista relación o que la relación sea más compleja que una tendencia, por ejemplo, una relación en forma de U).</p>
<p>– La magnitud nos indica la fuerza de la relación, que toma valores entre -1 a 1.</p>
<p>Cuanto más cercano sea el valor a los extremos del intervalo (1 o -1) más fuerte es la tendencia de las variables, o menor es la dispersión existe en los puntos alrededor de dicha tendencia. Cuanto más cercano sea a 0 sea el coeficiente de correlación, más débil será la tendencia, es decir, más dispersión habrá en la nube de puntos, como vemos en esta gráfica explicativa.</p>
<center>
<img src="https://i.ibb.co/swkRmLh/corr.png" width="350" />
</center>
<p><br></p>
<pre class="r"><code>cor(x, y, use = &quot;everything&quot;,
    method = c(&quot;pearson&quot;, &quot;kendall&quot;, &quot;spearman&quot;))</code></pre>
<p>Los parámetos de la función son:</p>
<ul>
<li><strong><em>x</em></strong>, <strong><em>y</em></strong>: vectores cuantitativos.</li>
<li>use: parámetro que indica lo que se debe hacer cuando se presenten registros NA en alguno de los vectores. Las diferentes posibilidades son: <strong><em>everything</em></strong>, <strong><em>all.obs</em></strong>, <strong><em>complete.obs</em></strong>, <strong><em>na.or.complete</em></strong> y <strong><em>pairwise.complete.obs</em></strong>, el valor por defecto es <strong><em>everything</em></strong>.</li>
<li>method: tipo de coeficiente de correlación a calcular, por defecto es <strong><em>pearson</em></strong>, otros valores posibles son <strong><em>kendall</em></strong> y <strong><em>spearman</em></strong>.</li>
</ul>
<blockquote>
<p><img src="https://i.ibb.co/Wkj4z61/alerta.gif" width="100" />
¡¡¡Atención, atención!!!</p>
Ten en cuenta que si tus datos contienen valores perdidos, deberas usar el siguiente código R para manejar los valores perdidos mediante la eliminación por caso.
</blockquote>
<pre class="r"><code>cor(data, use = &quot;complete.obs&quot;)</code></pre>
<p>Antes de continuar, para saber que tipo correlación aplicar es importante revisar los supuestos de las pruebas, en este ejercicio haremos las pruebas bajo el test de Normalidad de Shapiro-Wilk, como lo vimos en nuestro post <a href="https://rbiologos.com/blog/a014/"><em>Supuestos estadísticos</em></a>. Si nuestros datos presentan una distribución normal, la <em><em>Correlación de Pearson</em></em> es la prueba adecuada para nuestros datos.</p>
<div id="correlación-de-pearson" class="section level2">
<h2>Correlación de Pearson</h2>
<p><a name="4"></a></p>
<p>Es un coeficiente paramétrico que evalúa la relación lineal entre dos variables continuas. Una relación es lineal cuando un cambio en una variable se asocia con un cambio proporcional en la otra variable.</p>
<center>
<img src="https://i.ibb.co/L9d6qNn/down.gif" width="350" />
</center>
<p><br></p>
<p>Para este ejemplo usaremos la base de datos <res>Datos escarabajos</res>, la cual contiene los datos de un estudio de Escarabajos coprófagos y sus funciones ecológicas.</p>
<center>
<a href="https://min.gitcdn.link/repo/davidvaneal/Documentos-RBiologos/main/Datos%20escarabajos.csv"><img src="https://i.ibb.co/6gx1V1Y/csv-icon.png" alt="descarga" border="0" width="150"></a>
</center>
<center>
Descarga aquí
</center>
<p><br></p>
<p>Usaremos las variables Individuos y Dispersión, con el fin de encontrar su posible correlación. Primero realizamos el test de <em>Normalidad</em>, con el fin de saber que tipo de prueba de correlación vamos a realizar.</p>
<pre class="r"><code>url &lt;- &quot;https://raw.githubusercontent.com/davidvaneal/Documentos-RBiologos/main/Datos%20escarabajos.csv&quot;
esc &lt;- read.csv(url)

shapiro.test(esc$Especies)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  esc$Especies
## W = 0.88433, p-value = 0.1743</code></pre>
<pre class="r"><code>shapiro.test(esc$Dispersión)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  esc$Dispersión
## W = 0.91145, p-value = 0.3261</code></pre>
<p>De acuerdo a nuestros resultados tenemos una distribución normal para nuestras variables, por lo que podemos usar una <em><em>Correlación de Pearson</em></em> para evaluar si la riqueza de especies de los escarabajos tiene relación con la tasa de semillas dispersadas por estos (%).</p>
<pre class="r"><code>cor.test(esc$Especies, esc$Dispersión,
    method = c(&quot;pearson&quot;))</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  esc$Especies and esc$Dispersión
## t = 6.4253, df = 7, p-value = 0.0003586
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6751838 0.9843259
## sample estimates:
##       cor 
## 0.9246766</code></pre>
<p>Del resultado anterior vemos que existe una correlación de <em><strong><em>0.9246766</em></strong></em> entre las dos variables, lo que quiere decir que si hay relaciones estadísticas significativas entre la riqueza de especies de escarabajos coprófagos y la tasa de semillas dispersadas.</p>
<center>
<img src="https://i.ibb.co/d49yQP6/Wooo.gif" width="350" />
</center>
<p><br></p>
<p>Ahora observemos el comportamiento de los puntos en una gráfica (Fig. 1), mediante el paquete <em><em>ggplot2</em></em>.</p>
<p><img src="https://rbiologos.com/blog/a016/index.es_files/figure-html/unnamed-chunk-9-1.png" width="100%" /></p>
<p>Fig. 1. Riqueza de especies de escarabajos prófagos y la tasa de semillas dispersadas por parte de estos <a href="#anexo1">Anexo 1.</a></p>
<p>Claramente se observa un patrón de relación de la nube de puntos (Fig. 1), estos puntos no se observan dispersos y por tanto el valor del coeficiente de correlación.</p>
</div>
<div id="coeficiente-de-determinación" class="section level2">
<h2>Coeficiente de determinación</h2>
<p><a name="5"></a></p>
<p>El cuadrado del coeficiente de correlación de Pearson es, en si mismo, un estadístico de gran utilidad denominado coeficiente de determinación. Es una medida de la proporción de la variabilidad en una variable, atribuible a la variabilidad de la otra.</p>
<p>En otras palabras, ¿cual es la proporción de la variación total en Y que puede ser explicada por la variación en X?</p>
<p>Para este ejercicio tomaremos el valor de correlación del ejercicio anterior</p>
<pre class="r"><code>coeffdet &lt;- 0.9246766^2
coeffdet</code></pre>
<pre><code>## [1] 0.8550268</code></pre>
<p>Así podemos deducir que aproximadamente el 85.50% de la riqueza de especies de los escarabajos está relacionado con la tasa de semillas dispersadas.</p>
<center>
<img src="https://i.ibb.co/JtDkS1M/yes.gif" width="350" />
</center>
<p><br></p>
</div>
<div id="gráfico-de-correlaciones" class="section level2">
<h2>Gráfico de correlaciones</h2>
<p><a name="6"></a></p>
<p>Es posible representar gráficamente las matrices de correlaciones por medio de la función corrplot del paquete <res>corrplot</res> (Para obtener mayor información puedes consultar la siguiente página <a href="https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html"><em>An Introduction to corrplot Packaged</em></a>.</p>
<p>Para realizar este ejercicio vamos a utilizar los resultados de la correlación de la base de datos <res>Escarabajos</res> y todas sus variables, analizando en primera instancia su normalidad.</p>
<pre class="r"><code>lapply(esc, shapiro.test)</code></pre>
<pre><code>## $Individuos
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.96509, p-value = 0.8498
## 
## 
## $Especies
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.88433, p-value = 0.1743
## 
## 
## $Biomasa
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.82405, p-value = 0.03828
## 
## 
## $Longitud
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.87821, p-value = 0.1504
## 
## 
## $Heces
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.92558, p-value = 0.4405
## 
## 
## $Suelo
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.8997, p-value = 0.2503
## 
## 
## $Dispersión
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.91145, p-value = 0.3261</code></pre>
<p>Como podemos ver la única variable que no cumple con el supuesto de normalidad es <em><em>Biomasa</em></em>. Por lo que vamos a realizar nuestro análisis de correlación sin dicha variable.</p>
<pre class="r"><code>## Eliminamos la variable &quot;Biomasa&quot;
esc2 &lt;- esc[,-3]

## Cargamos el paquete para generar nuestro gráfico
library(corrplot)

## Seguimos con el análisis
esc.cor &lt;-round(cor(esc2), 4)
esc.cor</code></pre>
<pre><code>##            Individuos Especies Longitud   Heces   Suelo Dispersión
## Individuos     1.0000   0.8153   0.0896  0.8803  0.8847     0.9576
## Especies       0.8153   1.0000  -0.0105  0.8578  0.8572     0.9247
## Longitud       0.0896  -0.0105   1.0000 -0.1028 -0.1040     0.0066
## Heces          0.8803   0.8578  -0.1028  1.0000  0.8150     0.9335
## Suelo          0.8847   0.8572  -0.1040  0.8150  1.0000     0.9322
## Dispersión     0.9576   0.9247   0.0066  0.9335  0.9322     1.0000</code></pre>
<p>Y finalmente podemos hacer uso de las herramientas gráficas para poder visualizar de una manera más visual nuestros resultados</p>
<pre class="r"><code>## Definimos colores
col &lt;- colorRampPalette(c(&quot;#BB4444&quot;, &quot;#EE9988&quot;, &quot;#FFFFFF&quot;,
                          &quot;#77AADD&quot;, &quot;#4477AA&quot;))
## Y graficamos
corrplot(esc.cor, method = &quot;shade&quot;, sade.col = NA, tl.col = &quot;black&quot;, 
         tl.srt = 45, col = col(200), addCoef.col = &quot;black&quot;, 
         addcolorlabel = &quot;no&quot;, order = &quot;AOE&quot;, type = &quot;upper&quot;, diag = F)</code></pre>
<p><img src="https://rbiologos.com/blog/a016/index.es_files/figure-html/unnamed-chunk-13-1.png" width="100%" /></p>
<p>En este tipo de gráficos en la diagonal están las variables, por encima están los cuadros de colores, entre más intensidad del color, ya sea azul (positiva) o rojo (negativa), mayor es la correlación, donde los colores ténues significan correlación baja. Dentro de cada cuadro se observan los valores exactos de correlación.</p>
<center>
<img src="https://i.ibb.co/xzkRq9X/parkour.gif" width="350" />
</center>
<p><br></p>
<p>Como podemos observar en nuestro gráfico, se muestra la matriz con los coeficientes de correlación entre todas las variables, siendo la correlación más fuerte entre la <em>tasa de dispersión de semillas</em> y el <em>número de individuos</em>, y la más baja entre la <em>tasa de dispersión de semillas</em> y la <em>longitud de los escarabajos</em>.</p>
</div>
</div>
<div id="resumen" class="section level1">
<h1>Resumen</h1>
<p><a name="7"></a></p>
<p>Evidenciar una relación lineal entre dos variables parece ser sencillo bajo lo aprendido el día de hoy, sin embargo, es muy importante saber que detrás de todo ello hay matemática pura y dura que debemos tener muy en cuenta. Nosotros solamente te damos un pequeño empujón en el mundo de R, así que debes investigar y leer mucho más sobre estos temas.</p>
<center>
<img src="https://i.ibb.co/7vX0QHH/bye.gif" width="350" />
</center>
<p><br></p>
<p>Pudimos aprender un poco más sobre las relaciones paramétricas como las regresiones lineales simples y la correlación de Pearson. Sobre las regresiones lineales estudiamos los valores de sus resultados y como poder graficar para poder observar dicho comportamiento, recuerda que debemos observar y tener en cuenta nuestras gráficas y nuestros resultados para dar un dictamen más robusto. Asimismo, sobre la correlación de Pearson estudiamos sobre los signos y magnitudes de los resultados y como poder graficar dichos valores de resultados.</p>
<p>Muchas gracias por leernos, esperamos puedan aprender tanto como nosotros en este post ¡hasta pronto!</p>
<p>Ahhhh y aprovechamos para desearles una muy <strong><em>¡¡¡Feliz Navidad!!!</em></strong>, que esta festividad sea un símbolo de amor y paz en el corazón de todo el mundo, con grandes aprendizajes y momentos felices en familia y amigos, brindando por los que no pueden estar y los que vendrán.</p>
<center>
<img src="https://i.ibb.co/jvNk0gH/Christmas.gif" width="350" />
</center>
<p><br></p>
</div>
<div id="bibliografía" class="section level1">
<h1>Bibliografía</h1>
<p><a name="8"></a></p>
<ul>
<li><p><a href="https://www.cienciadedatos.net/documentos/24_correlacion_y_regresion_lineal#Correlaci%C3%B3n_lineal">Correlación lineal y Regresión lineal simple</a></p></li>
<li><p><a href="https://rpubs.com/osoramirez/316691">Correlación y Regresión Lineal</a></p></li>
<li><p><a href="https://fhernanb.github.io/Manual-de-R/correl.html#correl">Medidas de correlación</a></p></li>
<li><p><a href="https://bookdown.org/dietrichson/metodos-cuantitativos/coeficientes-de-correlacion.html#coeficiente-spearman">Coeficientes de correlación</a></p></li>
<li><p><a href="https://rpubs.com/revite19/719420">Correlación</a></p></li>
</ul>
</div>
<div id="anexos" class="section level1">
<h1>Anexos</h1>
<p><a name="9"></a></p>
<p><a name="anexo1"></a>Anexo 1</p>
<pre class="r"><code>ggplot(esc, aes(x = Individuos, y = Dispersión))+
      geom_point(col=&#39;blue&#39;)+
      scale_y_continuous(&quot;Dispersión de semillas (%)&quot;)+
      scale_x_continuous(&quot;Longitud escarabajos (mm)&quot;)+
      theme(axis.title.y = element_text(size = 16),
            axis.title.x = element_text(size = 16),
            axis.text.y = element_text(size = 13),
            axis.text.x = element_text(size = 13))+
      theme(panel.background = element_blank(), 
            panel.border = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.line = element_line(colour = &quot;black&quot;, size = 1))</code></pre>
</div>
<div id="más-información" class="section level1">
<h1>Más información</h1>
<p><a name="10"></a></p>
<p>Estos análisis se han realizado utilizando el software R (v.4.1.0) y Rstudio (v. 1.4.1717)</p>
<p>Recuerda que todos nuestros códigos están almacenados en <a href="https://github.com/RBiologos/Posts">GitHub</a></p>
<center>
<img src="https://i.ibb.co/DpKmR1k/github.png" width="350" />
</center>
</div>

        </div>
        
        

<div class="social-share pt-4">
	<h4>Comparte:</h4>
	
	<a class="resp-sharing-button__link" href="https://facebook.com/sharer/sharer.php?u=https%3a%2f%2frbiologos.com%2fblog%2fa016%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--facebook resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path d="M18.77 7.46H14.5v-1.9c0-.9.6-1.1 1-1.1h3V.5h-4.33C10.24.5 9.5 3.44 9.5 5.32v2.15h-3v4h3v12h5v-12h3.85l.42-4z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="https://twitter.com/intent/tweet/?text=Relaciones%20lineales&amp;url=https%3a%2f%2frbiologos.com%2fblog%2fa016%2f"
		target="_blank" rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--twitter resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M23.44 4.83c-.8.37-1.5.38-2.22.02.93-.56.98-.96 1.32-2.02-.88.52-1.86.9-2.9 1.1-.82-.88-2-1.43-3.3-1.43-2.5 0-4.55 2.04-4.55 4.54 0 .36.03.7.1 1.04-3.77-.2-7.12-2-9.36-4.75-.4.67-.6 1.45-.6 2.3 0 1.56.8 2.95 2 3.77-.74-.03-1.44-.23-2.05-.57v.06c0 2.2 1.56 4.03 3.64 4.44-.67.2-1.37.2-2.06.08.58 1.8 2.26 3.12 4.25 3.16C5.78 18.1 3.37 18.74 1 18.46c2 1.3 4.4 2.04 6.97 2.04 8.35 0 12.92-6.92 12.92-12.93 0-.2 0-.4-.02-.6.9-.63 1.96-1.22 2.56-2.14z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="https://plus.google.com/share?url=https%3a%2f%2frbiologos.com%2fblog%2fa016%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--google resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M11.37 12.93c-.73-.52-1.4-1.27-1.4-1.5 0-.43.03-.63.98-1.37 1.23-.97 1.9-2.23 1.9-3.57 0-1.22-.36-2.3-1-3.05h.5c.1 0 .2-.04.28-.1l1.36-.98c.16-.12.23-.34.17-.54-.07-.2-.25-.33-.46-.33H7.6c-.66 0-1.34.12-2 .35-2.23.76-3.78 2.66-3.78 4.6 0 2.76 2.13 4.85 5 4.9-.07.23-.1.45-.1.66 0 .43.1.83.33 1.22h-.08c-2.72 0-5.17 1.34-6.1 3.32-.25.52-.37 1.04-.37 1.56 0 .5.13.98.38 1.44.6 1.04 1.84 1.86 3.55 2.28.87.23 1.82.34 2.8.34.88 0 1.7-.1 2.5-.34 2.4-.7 3.97-2.48 3.97-4.54 0-1.97-.63-3.15-2.33-4.35zm-7.7 4.5c0-1.42 1.8-2.68 3.9-2.68h.05c.45 0 .9.07 1.3.2l.42.28c.96.66 1.6 1.1 1.77 1.8.05.16.07.33.07.5 0 1.8-1.33 2.7-3.96 2.7-1.98 0-3.54-1.23-3.54-2.8zM5.54 3.9c.33-.38.75-.58 1.23-.58h.05c1.35.05 2.64 1.55 2.88 3.35.14 1.02-.08 1.97-.6 2.55-.32.37-.74.56-1.23.56h-.03c-1.32-.04-2.63-1.6-2.87-3.4-.13-1 .08-1.92.58-2.5zM23.5 9.5h-3v-3h-2v3h-3v2h3v3h2v-3h3" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="mailto:?subject=Relaciones%20lineales&amp;body=https%3a%2f%2frbiologos.com%2fblog%2fa016%2f" target="_self"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--email resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M22 4H2C.9 4 0 4.9 0 6v12c0 1.1.9 2 2 2h20c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zM7.25 14.43l-3.5 2c-.08.05-.17.07-.25.07-.17 0-.34-.1-.43-.25-.14-.24-.06-.55.18-.68l3.5-2c.24-.14.55-.06.68.18.14.24.06.55-.18.68zm4.75.07c-.1 0-.2-.03-.27-.08l-8.5-5.5c-.23-.15-.3-.46-.15-.7.15-.22.46-.3.7-.14L12 13.4l8.23-5.32c.23-.15.54-.08.7.15.14.23.07.54-.16.7l-8.5 5.5c-.08.04-.17.07-.27.07zm8.93 1.75c-.1.16-.26.25-.43.25-.08 0-.17-.02-.25-.07l-3.5-2c-.24-.13-.32-.44-.18-.68s.44-.32.68-.18l3.5 2c.24.13.32.44.18.68z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link"
		href="https://reddit.com/submit/?url=https%3a%2f%2frbiologos.com%2fblog%2fa016%2f&amp;resubmit=true&amp;title=Relaciones%20lineales" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--reddit resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M24 11.5c0-1.65-1.35-3-3-3-.96 0-1.86.48-2.42 1.24-1.64-1-3.75-1.64-6.07-1.72.08-1.1.4-3.05 1.52-3.7.72-.4 1.73-.24 3 .5C17.2 6.3 18.46 7.5 20 7.5c1.65 0 3-1.35 3-3s-1.35-3-3-3c-1.38 0-2.54.94-2.88 2.22-1.43-.72-2.64-.8-3.6-.25-1.64.94-1.95 3.47-2 4.55-2.33.08-4.45.7-6.1 1.72C4.86 8.98 3.96 8.5 3 8.5c-1.65 0-3 1.35-3 3 0 1.32.84 2.44 2.05 2.84-.03.22-.05.44-.05.66 0 3.86 4.5 7 10 7s10-3.14 10-7c0-.22-.02-.44-.05-.66 1.2-.4 2.05-1.54 2.05-2.84zM2.3 13.37C1.5 13.07 1 12.35 1 11.5c0-1.1.9-2 2-2 .64 0 1.22.32 1.6.82-1.1.85-1.92 1.9-2.3 3.05zm3.7.13c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm9.8 4.8c-1.08.63-2.42.96-3.8.96-1.4 0-2.74-.34-3.8-.95-.24-.13-.32-.44-.2-.68.15-.24.46-.32.7-.18 1.83 1.06 4.76 1.06 6.6 0 .23-.13.53-.05.67.2.14.23.06.54-.18.67zm.2-2.8c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm5.7-2.13c-.38-1.16-1.2-2.2-2.3-3.05.38-.5.97-.82 1.6-.82 1.1 0 2 .9 2 2 0 .84-.53 1.57-1.3 1.87z" />
				</svg>
			</div>
		</div>
	</a>

	
	<a class="resp-sharing-button__link" href="whatsapp://send?text=Relaciones%20lineales%20https%3a%2f%2frbiologos.com%2fblog%2fa016%2f" target="_blank"
		rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--whatsapp resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M20.1 3.9C17.9 1.7 15 .5 12 .5 5.8.5.7 5.6.7 11.9c0 2 .5 3.9 1.5 5.6L.6 23.4l6-1.6c1.6.9 3.5 1.3 5.4 1.3 6.3 0 11.4-5.1 11.4-11.4-.1-2.8-1.2-5.7-3.3-7.8zM12 21.4c-1.7 0-3.3-.5-4.8-1.3l-.4-.2-3.5 1 1-3.4L4 17c-1-1.5-1.4-3.2-1.4-5.1 0-5.2 4.2-9.4 9.4-9.4 2.5 0 4.9 1 6.7 2.8 1.8 1.8 2.8 4.2 2.8 6.7-.1 5.2-4.3 9.4-9.5 9.4zm5.1-7.1c-.3-.1-1.7-.9-1.9-1-.3-.1-.5-.1-.7.1-.2.3-.8 1-.9 1.1-.2.2-.3.2-.6.1s-1.2-.5-2.3-1.4c-.9-.8-1.4-1.7-1.6-2-.2-.3 0-.5.1-.6s.3-.3.4-.5c.2-.1.3-.3.4-.5.1-.2 0-.4 0-.5C10 9 9.3 7.6 9 7c-.1-.4-.4-.3-.5-.3h-.6s-.4.1-.7.3c-.3.3-1 1-1 2.4s1 2.8 1.1 3c.1.2 2 3.1 4.9 4.3.7.3 1.2.5 1.6.6.7.2 1.3.2 1.8.1.6-.1 1.7-.7 1.9-1.3.2-.7.2-1.2.2-1.3-.1-.3-.3-.4-.6-.5z" />
				</svg>
			</div>
		</div>
	</a>
	
	<a class="resp-sharing-button__link" href="https://telegram.me/share/url?text=Relaciones%20lineales&amp;url=https%3a%2f%2frbiologos.com%2fblog%2fa016%2f"
		target="_blank" rel="noopener" aria-label="">
		<div class="resp-sharing-button resp-sharing-button--telegram resp-sharing-button--small">
			<div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
					<path
						d="M.707 8.475C.275 8.64 0 9.508 0 9.508s.284.867.718 1.03l5.09 1.897 1.986 6.38a1.102 1.102 0 0 0 1.75.527l2.96-2.41a.405.405 0 0 1 .494-.013l5.34 3.87a1.1 1.1 0 0 0 1.046.135 1.1 1.1 0 0 0 .682-.803l3.91-18.795A1.102 1.102 0 0 0 22.5.075L.706 8.475z" />
				</svg>
			</div>
		</div>
	</a>

</div>
        
        
        <div class="mt-5">
          
        </div>
      </div>
    </div>
  </div>
</section>


  </div><!-- end Contact Area -->
<footer id="footer" class="section-bg">
	<div class="container">
		<div class="row wow fadeInUp" data-wow-duration="500ms">
			<div class="col-lg-12">

			

                        <!-- Footer Social Links -->
				<div class="social-icon"><h1><center                                                    >Social</center></h1>
					<ul class="list-inline">
						
						<li class="list-inline-item"><a href="https://www.instagram.com/rbiologos/" target="blank"><i class="ti-instagram" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://www.facebook.com/rbiologos" target="blank"><i class="ti-facebook" target="blank"></i></a></li>
						
						<li class="list-inline-item"><a href="https://github.com/RBiologos/Posts" target="blank"><i class="ti-github" target="blank"></i></a></li>
						
					</ul>
				</div>
				
				<center><img src="https://i.ibb.co/SwJkbqh/2.png" alt="R Biólogos" height="200" /></center>
	
				<!-- copyright -->
				<div class="copyright text-center">
				        
					<a href="https://rbiologos.com/">
					</a>
					<br>
					<p1>Copyright © 2020 Modificado por <a href="https://davidvanegal.github.io/">David Vanegas</a> bajo la plantilla <a href="https://themefisher.com">Themefisher</a> de <a href="https://gethugothemes.com">HUGO</a></p1>
				</div>
				
			</div>
		</div>
	</div>
</footer>
<!-- /footer -->

<!-- Google Map API -->


<!-- JS Plugins -->

<script src="https://rbiologos.com/plugins/jquery/jquery.min.js"></script>

<script src="https://rbiologos.com/plugins/bootstrap/bootstrap.min.js"></script>

<script src="https://rbiologos.com/plugins/slick/slick.min.js"></script>

<script src="https://rbiologos.com/plugins/shuffle/shuffle.min.js"></script>

<script src="https://rbiologos.com/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>

<script src="https://rbiologos.com/plugins/lazy-load/lozad.min.js"></script>

<script src="https://rbiologos.com/plugins/google-map/map.js"></script>


<!-- Main Script -->

<script src="https://rbiologos.com/js/script.min.ab3836b70bc45170e8ff6dd572ee5e8e761ac8376daf9ceb40f760dfb6f2cce49672517da770a0049959f5fc93337e13.js" integrity="sha384-qzg2twvEUXDo/23Vcu5ejnYayDdtr5zrQPdg37byzOSWclF9p3CgBJlZ9fyTM34T"></script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
<div id="js-cookie-box" class="cookie-box cookie-box-hide">
	This site uses cookies. By continuing to use this website, you agree to their use. <span id="js-cookie-button" class="btn btn-transparent">I Accept</span>
</div>
<script>
	(function ($) {
		const cookieBox = document.getElementById('js-cookie-box');
		const cookieButton = document.getElementById('js-cookie-button');
		if (!Cookies.get('cookie-box')) {
			cookieBox.classList.remove('cookie-box-hide');
			cookieButton.onclick = function () {
				Cookies.set('cookie-box', true, {
					expires:  2 
				});
				cookieBox.classList.add('cookie-box-hide');
			};
		}
	})(jQuery);
</script>
</body>

</html>
